package Model;
// Generated 21/01/2019 23:56:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private Integer idAlumno;
     private Persona persona;
     private Set alumnoMaterias = new HashSet(0);
     private Asistencia asistencia;

    public Alumno() {
    }

    public Alumno(Persona persona) {
        this.persona = persona;
    }

    public Alumno(Persona persona, Set alumnoMaterias, Asistencia asistencia) {
       this.persona = persona;
       this.alumnoMaterias = alumnoMaterias;
       this.asistencia = asistencia;
    }
   
    public Integer getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(Integer idAlumno) {
        this.idAlumno = idAlumno;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Set getAlumnoMaterias() {
        return this.alumnoMaterias;
    }
    
    public void setAlumnoMaterias(Set alumnoMaterias) {
        this.alumnoMaterias = alumnoMaterias;
    }
    public Asistencia getAsistencia() {
        return this.asistencia;
    }
    
    public void setAsistencia(Asistencia asistencia) {
        this.asistencia = asistencia;
    }




}


