package Model;
// Generated 21/01/2019 23:56:54 by Hibernate Tools 4.3.1



/**
 * AlumnoMateria generated by hbm2java
 */
public class AlumnoMateria  implements java.io.Serializable {


     private Integer idAlumnoMateria;
     private Alumno alumno;
     private Materia materia;

    public AlumnoMateria() {
    }

    public AlumnoMateria(Alumno alumno, Materia materia) {
       this.alumno = alumno;
       this.materia = materia;
    }
   
    public Integer getIdAlumnoMateria() {
        return this.idAlumnoMateria;
    }
    
    public void setIdAlumnoMateria(Integer idAlumnoMateria) {
        this.idAlumnoMateria = idAlumnoMateria;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }




}


