package Model;
// Generated 21/01/2019 23:56:54 by Hibernate Tools 4.3.1



/**
 * Asistencia generated by hbm2java
 */
public class Asistencia  implements java.io.Serializable {


     private int idAlumno;
     private Alumno alumno;
     private Integer asistencia;
     private Integer personaDni;
     private Integer faltas;
     private Integer justificadas;
     private String observaciones;

    public Asistencia() {
    }

	
    public Asistencia(Alumno alumno) {
        this.alumno = alumno;
    }
    public Asistencia(Alumno alumno, Integer asistencia, Integer personaDni, Integer faltas, Integer justificadas, String observaciones) {
       this.alumno = alumno;
       this.asistencia = asistencia;
       this.personaDni = personaDni;
       this.faltas = faltas;
       this.justificadas = justificadas;
       this.observaciones = observaciones;
    }
   
    public int getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(int idAlumno) {
        this.idAlumno = idAlumno;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Integer getAsistencia() {
        return this.asistencia;
    }
    
    public void setAsistencia(Integer asistencia) {
        this.asistencia = asistencia;
    }
    public Integer getPersonaDni() {
        return this.personaDni;
    }
    
    public void setPersonaDni(Integer personaDni) {
        this.personaDni = personaDni;
    }
    public Integer getFaltas() {
        return this.faltas;
    }
    
    public void setFaltas(Integer faltas) {
        this.faltas = faltas;
    }
    public Integer getJustificadas() {
        return this.justificadas;
    }
    
    public void setJustificadas(Integer justificadas) {
        this.justificadas = justificadas;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


