package Model;
// Generated 21/01/2019 23:56:54 by Hibernate Tools 4.3.1



/**
 * Directivo generated by hbm2java
 */
public class Directivo  implements java.io.Serializable {


     private int idPersona;
     private Persona persona;

    public Directivo() {
    }

    public Directivo(Persona persona) {
       this.persona = persona;
    }
   
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }




}


