package Model;
// Generated 21/01/2019 23:56:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Materia generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


     private Integer idMateria;
     private String nombre;
     private Set alumnoMaterias = new HashSet(0);

    public Materia() {
    }

    public Materia(String nombre, Set alumnoMaterias) {
       this.nombre = nombre;
       this.alumnoMaterias = alumnoMaterias;
    }
   
    public Integer getIdMateria() {
        return this.idMateria;
    }
    
    public void setIdMateria(Integer idMateria) {
        this.idMateria = idMateria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getAlumnoMaterias() {
        return this.alumnoMaterias;
    }
    
    public void setAlumnoMaterias(Set alumnoMaterias) {
        this.alumnoMaterias = alumnoMaterias;
    }




}


