package Model;
// Generated 21/01/2019 23:56:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer idPersona;
     private String nombre;
     private String apellido;
     private Date fechaNacimiento;
     private String direccion;
     private Integer telefono;
     private String cargo;
     private int dni;
    // private Set alumnos = new HashSet(0);
     private Profesor profesor;
    // private Set usuarios = new HashSet(0);
     private Directivo directivo;
     private Usuario usuario;

    public Usuario getUsuario() {
        return usuario;
    }

    public Persona(int dni, String apellido, String nombre, Date fechaNacimiento, String direccion ) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.fechaNacimiento = fechaNacimiento;
        this.direccion = direccion;
        this.dni = dni;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public Persona() {
    }

	
    public Persona(int dni) {
        this.dni = dni;
    }
    public Persona(String nombre, String apellido, Date fechaNacimiento, String direccion, Integer telefono, String cargo, int dni, Profesor profesor, Directivo directivo, Usuario usuario) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechaNacimiento = fechaNacimiento;
       this.direccion = direccion;
       this.telefono = telefono;
       this.cargo = cargo;
       this.dni = dni;
       //this.alumnos = alumnos;
       this.profesor = profesor;
       //this.usuarios = usuarios;
       this.directivo = directivo;
       this.usuario = usuario;
    }
   
    public Persona(String nombre, String apellido, Date fechaNacimiento, String direccion, Integer telefono, String cargo, int dni) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechaNacimiento = fechaNacimiento;
       this.direccion = direccion;
       this.telefono = telefono;
       this.cargo = cargo;
       this.dni = dni;
    }
    
public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    //public Set getAlumnos() {
     //   return this.alumnos;
    //}
    
    //public void setAlumnos(Set alumnos) {
    //    this.alumnos = alumnos;
    //}
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    //public Set getUsuarios() {
    //    return this.usuarios;
    //}
    
    //public void setUsuarios(Set usuarios) {
    //    this.usuarios = usuarios;
    //}
    public Directivo getDirectivo() {
        return this.directivo;
    }
    
    public void setDirectivo(Directivo directivo) {
        this.directivo = directivo;
    }




}


