package Model;
// Generated 21/01/2019 23:56:54 by Hibernate Tools 4.3.1

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Persona persona;
     private String pass;

    public Usuario() {
    }
	
    public Usuario(Persona persona) {
        this.persona = persona;
    }
    public Usuario(Persona persona, String pass) {
       this.persona = persona;
       this.pass = pass;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }

}


